import React from 'react';
import Head from 'next/head';
import Navbar from '../header/Navbar';
import Sidebar from '../header/Sidebar';
import styles from './layout.module.css'; 

type Props = {
  children: React.ReactNode;
};

const Layout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Martin Drozdik</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <main className='relative overflow-x-hidden'>
        <Sidebar />
        <Navbar />
        {children}
      </main>
    </>
  );
};

export default Layout;
